---
- name: Install essential packages
  apt:
    name:
      - curl
      - wget
      - git
      - unzip
      - software-properties-common
      - apt-transport-https
      - ca-certificates
      - gnupg
      - lsb-release
      - python3-pip
      - python3-setuptools
      - python3-dev
      - build-essential
      - htop
      - rsync
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Add Google Cloud SDK repository
  shell: |
    echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
  args:
    creates: /etc/apt/sources.list.d/google-cloud-sdk.list

- name: Import Google Cloud SDK GPG key
  shell: |
    curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
  args:
    creates: /usr/share/keyrings/cloud.google.gpg

- name: Install Google Cloud SDK
  apt:
    name: google-cloud-cli
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Create docker group
  group:
    name: docker
    state: present

- name: Create airflow user
  user:
    name: airflow
    system: yes
    shell: /bin/bash
    home: /home/airflow
    create_home: yes
    uid: "{{ airflow_uid }}"
    groups: docker

- name: Create airflow directories
  file:
    path: "{{ item }}"
    state: directory
    owner: airflow
    group: airflow
    mode: '0755'
  loop:
    - "{{ airflow_project_dir }}"
    - "{{ airflow_project_dir }}/dags"
    - "{{ airflow_project_dir }}/logs"
    - "{{ airflow_project_dir }}/plugins"
    - "{{ airflow_project_dir }}/config"
    - "{{ airflow_project_dir }}/credentials"

- name: Set up environment variables
  template:
    src: ../../templates/environment.j2
    dest: /etc/environment
    mode: '0644'
  notify: reload environment 