---
- name: Deploy Airflow to GCP VM
  hosts: airflow_servers
  gather_facts: yes
  become: yes
  
  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

  roles:
    - role: common
    - role: docker
    - role: airflow
    - role: nginx
    - role: monitoring 